const fs = require("fs");
const path = require("path");

const dirs = [
  path.join(__dirname, "src/pages"),
  path.join(__dirname, "src/components")
];

let filesProcessed = 0;
let occurrencesRemoved = 0;

function walk(dir) {
  const files = fs.readdirSync(dir);
  for (const file of files) {
    const fullPath = path.join(dir, file);
    if (fs.statSync(fullPath).isDirectory()) {
      walk(fullPath);
    } else if (fullPath.endsWith(".jsx")) {
      let content = fs.readFileSync(fullPath, "utf-8");
      if (content.includes("px-[5%]")) {
        const initialLen = content.length;
        content = content.replace(/px-\[5%\]/g, "");
        // Clean up any double spaces generated by the replacement
        content = content.replace(/  +/g, " ");
        content = content.replace(/ \)/g, ")");
        content = content.replace(/ \]/g, "]");
        fs.writeFileSync(fullPath, content);
        filesProcessed++;
        
        // Count occurrences
        const diff = initialLen - content.length;
        occurrencesRemoved += (diff / 7); // approx
      }
    }
  }
}

dirs.forEach(walk);
console.log(`Removed px-[5%] from ${filesProcessed} files.`);
